baseURL: ''
title: "Dominik Michalski"
theme: PaperMod

languages:
  en:
    contentDir: content/en
    languageName: ":gb:"
    weight: 2
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: skills
          name: Skills
          url: /posts/
          weight: 20
        - identifier: projects
          name: My Projects
          url: "/projects/"
          weight: 30
        - identifier: cv
          name: Download CV
          url: "/CV Dominik Michalski.pdf"
          weight: 40
    params:
      homeInfoParams:
        Title: "Hi, I’m Dominik \U0001F44B"
        Lang: "en"

  pl:
    contentDir: content/pl
    languageName: "🇵🇱"
    weight: 2
    menu:
      main:
        - identifier: home
          name: O mnie
          url: /
          weight: 10
        - identifier: skills
          name: Umiejętności
          url: /skills/
          weight: 20
        - identifier: projects
          name: Projekty
          url: "/projects/"
          weight: 30
        - identifier: cv
          name: Pobierz CV
          url: "/CV Dominik Michalski.pdf"
          weight: 40
    params:
      homeInfoParams:
        Title: "Cześć, nazywam się Dominik \U0001F44B"
        Lang: "pl"

params:
  socialIcons:
    - name: instagram
      url: ""
    - name: github
      url: ""
    - name: linkedin
      url: ""
  displayFullLangName: true


