baseURL: ''
languageCode: en-uk
title: "Dominik Portfolio"
theme: PaperMod

languages:
  en:
    languageName: "English"
    weight: 2
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: posts
          name: Blog
          url: /posts/
          weight: 20
        - identifier: projects
          name: Projects
          url: "/projects/"
          weight: 30

  pl:
    languageName: "Polish"
    weight: 2
    menu:
      main:
        - identifier: home
          name: Strona Główna
          url: /
          weight: 10
        - identifier: posts
          name: Blog
          url: /posts/
          weight: 20
        - identifier: projects
          name: Projekty
          url: "/projects/"
          weight: 30

params:
  homeInfoParams:
    Title: "Hey, I’m Dominik \U0001F44B"
    Content: Test Content.
  socialIcons:
    - name: instagram
      url: ""
    - name: github
      url: ""
    - name: linkedin
      url: ""
  displayFullLangName: true


