baseURL: ''
title: "Dominik Michalski"
theme: dmichalski

languages:
  en:
    contentDir: content/en
    languageName: ":gb:"
    weight: 2
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: skills
          name: Skills
          url: /skills/
          weight: 20
        - identifier: projects
          name: My Projects
          url: /projects/
          weight: 30
    params:
      homeInfoParams:
        Title: "Hi, I’m Dominik \U0001F44B"
        Lang: "en"

  pl:
    contentDir: content/pl
    languageName: "🇵🇱"
    weight: 2
    menu:
      main:
        - identifier: home
          name: O mnie
          url: /pl
          weight: 10
        - identifier: skills
          name: Umiejętności
          url: /pl/skills/
          weight: 20
        - identifier: projects
          name: Projekty
          url: /pl/projects/
          weight: 30
    params:
      homeInfoParams:
        Title: "Cześć, nazywam się Dominik \U0001F44B"
        Lang: "pl"

params:
  socialIcons:
    - name: instagram
      url: ""
    - name: github
      url: ""
    - name: linkedin
      url: ""
  displayFullLangName: true


